######################## default configuration ####################
baseURL = "http://examplesite.org/"
title = "Bigspring Hugo"
theme = "bigspring"
# post pagination
paginate = "3"
# post excerpt
summaryLength = "15"
# default language
defaultContentLanguage = "en"
# disable language
disableLanguages = ["de"]
# disqus short name
disqusShortname = "" # get your shortname form here : https://disqus.com
# google analytics
googleAnalytics = "" # example : UA-123-45
# unsafe html
[markup.goldmark.renderer]
unsafe = true
