footer_left = []
footer_middle = []
[[footer_right]]
name = "Metarank Github"
url = "https://github.com/metarank/metarank"
[[main]]
name = "Home"
url = "/"
weight = 1
[[main]]
name = "About Us"
url = "about"
weight = ""
[[main]]
name = "Blog"
url = "blog"
weight = ""
