footer_right = []
[[footer_left]]
name = "About Us"
url = "#"
[[footer_middle]]
name = "Pricing"
url = "pricing"
[[footer_middle]]
name = "Platform"
url = "#"
[[footer_middle]]
name = "Features"
url = "#"
[[main]]
name = "About Us"
url = "about"
weight = ""
[[main]]
name = "Home"
url = "/"
weight = 1
